/**
 * tools/lib/release.mjs — **发行打包的领域模型**（"变更集 → 两种形状"的那半边）
 *
 * 一句话：把**当前所有变更过的资源**算出来，然后铺成两种形状 ——
 *   ① **测试安装树**（旧仓 `install/` 的等价物：基础树 + 覆盖件；ALF 走硬链接）
 *   ② **发行包**（旧仓 `patch/` 的等价物：一个 zip，只有玩家要的那几件）
 *
 * ## 为什么两条命令共用一个模型
 * 两者**输入完全相同**（变更集），差的只是"铺成什么形状"。变更集的算法只写一遍，
 * 于是"装进测试树的"与"发给玩家的"**必然是同一批字节** —— 这正是旧仓最容易漂的地方
 * （`patch/patch.config.json` 是一份手维护清单，实测与 `patch.json` 的键差 2 支：`$1$SCINIT.BIN` /
 *  `$1$SCJUMP.BIN` 没进包、`$3$DPINIT.BIN` / `$5$AMINIT2.BIN` 多出来）。
 *
 * ## 变更集 = 三处真源（**没有第四处**）
 * | 件 | 真源 | 谁是"变了"的判据 |
 * |---|---|---|
 * | `*.BIN`（453 支） | `data/translations/patch.json` 的**键** | 基线 + patch 重建出来的字节（`resultSha` 逐支复核） |
 * | `*.AGF`（10 张） | `tools/ui-bake/recipes/*.json` 的**配方集合** | `pnpm tools ui-bake build` 的产物 `dist/ui-bake/<块>.AGF` |
 * | `AGERC.DLL`（1 个） | `corpus/assets/agerc/AGERC.DLL`（可信产物，见 `release/README.md` §5.2） | 入库件本身就是成品 |
 *
 * ★ **不存同步清单**：旧仓 `patch.config.json` 那种"再把上面三处的结论抄一遍"的文件，
 *   是第二真源 —— 抄的那一刻起就注定与真源漂。清单在这里是**算出来的**。
 * ★ **AGF 不由本工具烧**：烧 AGF 要 headless Chrome（沙箱里要提权），那是 `tools/ui-bake.mjs` 的活；
 *   本工具**只消费它的产物**，缺产物就报"先跑哪条命令"，不自己凑一张图。
 *
 * ## 两条写路径的共同纪律
 * 写前：把所有问题一次算完（缺件 / 键集不符 / 版本节不合规格 ⇒ **一个字都不写**）；
 * 写后：**回读复验**（zip 逐条目反解比对；安装树的覆盖件逐个 sha256、ALF 逐个 ino 比对），
 *       不绿就回滚（zip 删掉、本次写入的覆盖件删掉）。
 */
import fs from 'node:fs';
import path from 'node:path';

import { openRoot } from './bin-source.mjs';
import { runCapture } from './exec.mjs';
import { sha256buf } from './fsx.mjs';
import { loadManifest } from './manifest.mjs';
import {
  DEFAULT_PATCH,
  DEFAULT_SUBS,
  loadPatch,
  mapperContext,
  rebuildBin,
  rootFromManifest,
  structuralProblems,
} from './patch.mjs';
import { DEFAULT_MANIFEST, REPO_ROOT } from './paths.mjs';
import { listRecipes } from './ui-bake/recipe.mjs';
import { buildZip, readZip } from './zip.mjs';

// ─────────────────────────────────────────────────────────── 落点与口径

export const DEFAULT_INSTALL_DIR = path.join(REPO_ROOT, 'dist', 'install');
export const DEFAULT_INSTALL_MANIFEST = path.join(REPO_ROOT, 'dist', 'install-manifest.json');
export const DEFAULT_PATCH_DIR = path.join(REPO_ROOT, 'dist', 'patch');
export const DEFAULT_BAKED_DIR = path.join(REPO_ROOT, 'dist', 'ui-bake');
export const DEFAULT_AGERC = path.join(REPO_ROOT, 'corpus', 'assets', 'agerc', 'AGERC.DLL');
export const DEFAULT_FONTS_DIR = path.join(REPO_ROOT, 'corpus', 'assets', 'fonts');
export const DEFAULT_RELEASE_DIR = path.join(REPO_ROOT, 'release');

/** 发行文本（随包发给玩家；真源在 `release/`，规格见 `release/README.md` §4） */
export const RELEASE_TEXTS = ['CHANGELOG.md', '安装说明.md'];

/** 发行字体（`Amayui-CN_cnjp{,-Bold}.ttf`；上游 Sarasa 基底**不**随包发） */
export const FONT_RE = /^Amayui-CN_cnjp.*\.ttf$/i;

/** 生成的 Locale Emulator 启动器（可选；旧仓 `install/` 里就有这么一份，本工具按 `--le-cmd` 现写） */
export const LE_LAUNCHER_NAME = '启动游戏-LE.cmd';

/**
 * LE 启动器的内容（**全 ASCII**：cmd 按 ANSI 码页解码，中文 `rem` 会变乱码 —— 旧仓那份就是这样）。
 * ★ 关键在 `cd /d "%~dp0"`：引擎按**当前目录**找自己的件；从 shell 菜单/别处启动时当前目录可能不是游戏目录。
 *   用 `%~dp0` 而不是写死绝对路径 ⇒ 整棵树搬到哪都能用。
 */
export function leLauncher(ctx) {
  const problems = [];
  if (!ctx.leCmd) return { buf: null, problems };
  if (!fs.existsSync(ctx.leCmd)) {
    problems.push(`Locale Emulator 的 LEProc 不在：${ctx.leCmd}（--le-cmd 给的路径不对？旧仓那份 cmd 里记的是它自己的安装位置）`);
    return { buf: null, problems };
  }
  const lines = [
    '@echo off',
    'rem Launch AGE.EXE through Locale Emulator (Japanese / CP932), with THIS folder as the working directory.',
    'rem The cd line matters: the engine resolves its own files against the current directory.',
    'rem Generated by: pnpm tools release install --le-cmd "<LEProc.exe>" [--le-profile <guid>]',
    'cd /d "%~dp0"',
    `start "" "${ctx.leCmd}"${ctx.leProfile ? ` -runas ${ctx.leProfile}` : ''} "%~dp0AGE.EXE"`,
    '',
  ];
  return { buf: Buffer.from(lines.join('\r\n'), 'latin1'), problems: [] };
}

/**
 * **基础树里不进测试树**的文件 —— 每条都必须有理由，理由写在代码里（唯一真源），文档只引用。
 * ★ 判据不是"看着碍事"，而是"它会让测试树**测不出真东西**"或"它不是游戏自身的件"。
 */
export const INSTALL_EXCLUDES = [
  {
    name: '天结.exe',
    why: '心愿屋汉化壳：本项目测的是**原版引擎 + 我们的数据**（安装说明里也不涉及它）',
  },
  {
    name: 'AGE-EXTEND.TTF',
    why: '引擎内置字体：不移出则游戏设置里的字体不生效、中文渲染不出来（安装说明第 2 步）',
  },
  { re: /\.dmp$/i, why: '崩溃转储垃圾（本机产物，不是游戏件）' },
  // ★ 下面三条 = **本机脱壳分析的派生物**（M1b：脱壳件 / 节表修补件 / IDA 库）。
  //   它们躺在游戏根目录里但**不是游戏自己的件**（少说 66 MB，其中 IDA 库 62 MB）；
  //   真按"基础树 = 游戏安装根"原样搬进测试树只会往里塞垃圾。
  { re: /\.idb$/i, why: 'IDA 数据库（本机脱壳分析的派生物，不是游戏件）' },
  { re: /__(?:AsProtect|dumped|info|userdata)\./i, why: '本机脱壳分析的派生物（脱壳件 / 节表修补件，不是游戏件）' },
  { re: /_unpacked\./i, why: '本机脱壳分析的派生物（脱壳产物，不是游戏件）' },
];

/** 排除项判据：命中返回理由，否则 null（`extra` 是命令行追加的 `--exclude <名字>`） */
export function excludeReason(name, extra = []) {
  for (const e of INSTALL_EXCLUDES) {
    if (e.name && e.name.toLowerCase() === String(name).toLowerCase()) return e.why;
    if (e.re && e.re.test(name)) return e.why;
  }
  for (const n of extra) if (String(n).toLowerCase() === String(name).toLowerCase()) return '命令行 --exclude';
  return null;
}

/** `dist/` 里的相对路径（打印用；不在工作区内就原样） */
export function relToRepo(p) {
  const r = path.relative(REPO_ROOT, p);
  return r && !r.startsWith('..') ? r.split(path.sep).join('/') : p;
}

// ─────────────────────────────────────────────────────────── 完整性标签（Windows 环境口径）

/**
 * 这个件/目录是不是被打上了 **Low 完整性标签**（`Mandatory Label\Low Mandatory Level`）。
 *
 * ★ **为什么这属于打包要管的事**（实测，2026-10）：**从带 Low 标签的 EXE 起的进程本身就是 Low 完整性**
 *   （`whoami /groups` 报 `Mandatory Label\Low Mandatory Level S-1-16-4096`）⇒
 *   - 游戏自己写 `%LOCALAPPDATA%\Eushully\…`（Medium）会被拒；
 *   - **Locale Emulator 那一步会失败**（它的注入 / 注册表重定向要跟 Medium 的对象打交道）——
 *     现象正好是"**进程起来了、窗口没有建出来**"，而直接双击（不经 LE）却能看到窗口（只是没转码）。
 * ★ **标签不是本工具打的**：受限沙箱（本仓开发时用的 DSH 沙箱）给**工作区里新建的每个文件**继承一个 Low 标签。
 *   所以"这类会话里建的树"要用 `--relabel-medium` 或在**工作区之外**建（`--out` 指到别处）。
 * @returns {{low:boolean, detail:string, error?:string}}
 */
export function lowIntegrityLabel(target, run = runCapture) {
  if (process.platform !== 'win32') return { low: false, detail: '（非 Windows，不适用）' };
  const r = run(path.dirname(target), 'icacls', [target]);
  if (r.error) return { low: false, detail: '', error: r.error };
  const line = (r.out.match(/Mandatory Label\\[^\r\n]*/) ?? [''])[0].trim();
  return { low: /Mandatory Label\\Low Mandatory Level/.test(r.out), detail: line };
}

/** 把一棵树（或一个件）的完整性改成 Medium：`icacls <目标> /setintegritylevel Medium /T /C` */
export function relabelMedium(target, run = runCapture) {
  if (process.platform !== 'win32') return { ok: false, reason: '非 Windows，不适用' };
  const r = run(path.dirname(target), 'icacls', [target, '/setintegritylevel', 'Medium', '/T', '/C']);
  if (r.error) return { ok: false, reason: r.error };
  if (r.code !== 0) return { ok: false, reason: `icacls 退出 ${r.code}（多半是权限不足：改完整性标签要提权 / 要写主 ACL）` };
  return { ok: true, out: r.out };
}

/** Low 标签的处置提示（给 CLI 打印用；措辞里带**可直接粘的命令**） */
export function lowLabelAdvice(target) {
  return [
    `${target} 被打了 **Low 完整性标签**（来源：DSH 0.2 的 Windows ACL 沙箱按设计给工作区打的常驻标签；见 tools/release.md §3.1）`,
    '★ 后果（实测）：**从带 Low 标签的 EXE 起的进程就是 Low 完整性**（`whoami /groups` = S-1-16-4096）⇒',
    '  游戏写自己的存档目录会被拒；**Locale Emulator 起不来**（现象：进程起来了、窗口没建出来；直接双击却能看到窗口只是没转码）。',
    '★ 修法（**推荐 ①**）：',
    '   ① 把树建到受限工作区**之外**（同卷 ⇒ ALF 硬链接照旧）：`--out E:\\Projects\\amayui-test-install`',
    '   ② 就地改标签（快，但有代价）：`--relabel-medium`（= `icacls "<树>" /setintegritylevel Medium /T /C`）',
    '      ★ 代价：改完这棵子树就落在**沙箱可写范围之外**了（受限子进程只能写带 Low 标签的根）——',
    '        下一次在沙箱会话里往这里写（例如重跑 release install）会 Access denied；要么提权跑，要么改完再重建时重新 --relabel-medium。',
  ];
}


/**
 * 把散在各处的参数收敛成一份上下文（**所有根都可覆盖** ⇒ 测试能用夹具，不必有游戏安装目录）。
 * @param {object} [opts]
 */
export function loadContext(opts = {}) {
  const manifest = opts.manifest ?? loadManifest(DEFAULT_MANIFEST);
  return {
    manifest,
    baseDir: opts.base ?? rootFromManifest(manifest, 'gameInstall'),
    patchPath: opts.patch ?? DEFAULT_PATCH,
    subsPath: opts.subs ?? DEFAULT_SUBS,
    bakedDir: opts.baked ?? DEFAULT_BAKED_DIR,
    agerc: opts.agerc ?? DEFAULT_AGERC,
    fontsDir: opts.fonts ?? DEFAULT_FONTS_DIR,
    releaseDir: opts.releaseDir ?? DEFAULT_RELEASE_DIR,
    /** AGF 进包集合：缺省 = 有配方的那批（`ui-bake` 的配方集合就是"我们改过哪些图"的真源） */
    blocks: opts.blocks ?? null,
    /** ALF 走硬链接（缺省）还是真拷贝：`copy` 只用在"不同卷 / 拿不到权限"的机器上 */
    alfMode: opts.alfMode === 'copy' ? 'copy' : 'hardlink',
    /** 可选：写一份 LE 启动器（`--le-cmd <LEProc.exe>` + `--le-profile <guid>`） */
    leCmd: opts.leCmd ?? null,
    leProfile: opts.leProfile ?? null,
    outDir: opts.out ?? DEFAULT_INSTALL_DIR,
    installManifest: opts.installManifest ?? DEFAULT_INSTALL_MANIFEST,
    zipDir: opts.zipDir ?? DEFAULT_PATCH_DIR,
    zipPath: opts.zip ?? null,
    packManifest: opts.packManifest ?? null,
    exclude: opts.exclude ?? [],
  };
}

// ─────────────────────────────────────────────────────────── 变更集

/**
 * 算变更集（读 + 重建 + 逐支复核）。
 *
 * @param {ReturnType<typeof loadContext>} ctx
 * @param {{onProgress?: (done:number,total:number)=>void}} [opts]
 * @returns {{bins:Array, agfs:Array, agerc:object|null, problems:string[], warnings:string[], stats:object}}
 */
export function collectChanged(ctx, { onProgress } = {}) {
  const problems = [];
  const warnings = [];

  // ── ① BIN：键集来自 patch.json；字节由「基线 + patch」重建 ──
  const bins = [];
  if (!fs.existsSync(ctx.patchPath)) {
    problems.push(`patch 不在：${ctx.patchPath}（先 pnpm tools patch extract --write）`);
  } else {
    const doc = loadPatch(ctx.patchPath);
    const structural = structuralProblems(doc);
    for (const p of structural) problems.push(`patch 结构不变量：${p}`);
    if (!structural.length) {
      const { mapper, subsSha } = mapperContext(ctx.subsPath);
      if (doc.subsSha !== subsSha) {
        warnings.push(`字典指纹与 patch 记录不一致（patch ${doc.subsSha.slice(0, 12)}… / 当前 ${subsSha.slice(0, 12)}…）—— 重建结果可能对不上 resultSha`);
      }
      let base;
      try {
        base = openRoot(ctx.baseDir);
      } catch (err) {
        problems.push(`基线根打不开：${err.message}`);
        base = null;
      }
      const names = Object.keys(doc.scripts).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
      for (const [i, name] of names.entries()) {
        const entry = doc.scripts[name];
        if (!base) break;
        const hit = base.resolve(name);
        if (!hit) {
          problems.push(`${name}：基线解析不出来（散装没有、ALF 里也没有）`);
          continue;
        }
        let buf;
        try {
          buf = rebuildBin(hit.buf, entry, { lineToBin: mapper.lineToBin });
        } catch (err) {
          problems.push(`${name}：重建失败 —— ${err.message}`);
          continue;
        }
        const sha256 = sha256buf(buf);
        if (sha256 !== entry.resultSha) {
          problems.push(`${name}：重建结果与 resultSha 不符（重建 ${sha256.slice(0, 12)}… / 记录 ${entry.resultSha.slice(0, 12)}…）`);
          continue;
        }
        bins.push({ name, buf, sha256, ops: entry.ops.length, baseFrom: hit.from });
        if (onProgress && (i + 1) % 25 === 0) onProgress(i + 1, names.length);
      }
    }
  }

  // ── ② AGF：集合来自配方，字节来自 ui-bake 的构建产物（本工具不烧图） ──
  const blocks = ctx.blocks ?? listRecipes();
  const agfs = [];
  for (const block of blocks) {
    const file = path.join(ctx.bakedDir, `${block}.AGF`);
    if (!fs.existsSync(file)) {
      problems.push(`AGF 缺件 ${relToRepo(file)} —— 先跑 \`pnpm tools ui-bake build\`（烧图要 headless Chrome，见 tools/ui-bake.md §5.1）`);
      continue;
    }
    const buf = fs.readFileSync(file);
    agfs.push({ block, name: `${block}.AGF`, buf, sha256: sha256buf(buf), file: relToRepo(file) });
  }

  // ── ③ AGERC.DLL：入库的可信产物 ──
  let agerc = null;
  if (!fs.existsSync(ctx.agerc)) {
    problems.push(`AGERC.DLL 不在：${relToRepo(ctx.agerc)}（清单条目 binary/agerc-dist）`);
  } else {
    const buf = fs.readFileSync(ctx.agerc);
    agerc = { name: 'AGERC.DLL', buf, sha256: sha256buf(buf), file: relToRepo(ctx.agerc) };
  }

  return {
    bins,
    agfs,
    agerc,
    problems,
    warnings,
    stats: { bins: bins.length, ops: bins.reduce((a, b) => a + b.ops, 0), agfs: agfs.length, agerc: agerc ? 1 : 0 },
  };
}

// ─────────────────────────────────────────────────────────── 发行包（zip）

/**
 * 版本节：取 `release/CHANGELOG.md` 的**第一个** `## v…` 节。
 * 形态只有两种（规格见 `release/README.md` §4）：`## v1.14（开发中）` / `## v1.14（2026-10-03）`。
 * @returns {null | {version:string, mark:string, dev:boolean, date:string|null, zipName:string|null}}
 */
export function changelogVersion(text) {
  const m = /^##[ \t]+(v\d+(?:\.\d+)*)[ \t]*[（(][ \t]*([^）)\r\n]*?)[ \t]*[）)][ \t]*$/m.exec(String(text ?? ''));
  if (!m) return null;
  const [, version, mark] = m;
  const dev = /开发中/.test(mark);
  const date = /^(\d{4})-(\d{2})-(\d{2})$/.exec(mark.trim());
  return {
    version,
    mark: mark.trim(),
    dev,
    date: date ? date[0] : null,
    // 与旧仓 zip 命名一脉相承：发布版 `v1.13-260901.zip`；未发布（开发中）用 `-dev` 且**不编日期**
    zipName: dev ? `${version}-dev.zip` : date ? `${version}-${date[1].slice(2)}${date[2]}${date[3]}.zip` : null,
  };
}

/** 发行字体（`corpus/assets/fonts/Amayui-CN_cnjp*.ttf`） */
export function distributionFonts(ctx) {
  const problems = [];
  if (!fs.existsSync(ctx.fontsDir)) return { fonts: [], problems: [`字体目录不在：${relToRepo(ctx.fontsDir)}`] };
  const names = fs.readdirSync(ctx.fontsDir).filter((n) => FONT_RE.test(n)).sort();
  if (!names.length) problems.push(`字体目录里没有 Amayui-CN_cnjp*.ttf：${relToRepo(ctx.fontsDir)}`);
  const fonts = names.map((n) => {
    const buf = fs.readFileSync(path.join(ctx.fontsDir, n));
    return { name: n, buf, sha256: sha256buf(buf), file: `${relToRepo(ctx.fontsDir)}/${n}` };
  });
  return { fonts, problems };
}

/** 随包文本（`release/CHANGELOG.md` · `release/安装说明.md`；**逐字复制**，不改一个字节） */
export function releaseTexts(ctx, names = RELEASE_TEXTS) {
  const problems = [];
  const texts = [];
  for (const n of names) {
    const f = path.join(ctx.releaseDir, n);
    if (!fs.existsSync(f)) { problems.push(`随包文本不在：${relToRepo(f)}`); continue; }
    const buf = fs.readFileSync(f);
    texts.push({ name: n, buf, sha256: sha256buf(buf), file: relToRepo(f) });
  }
  return { texts, problems };
}

/**
 * 发行包的**条目表**（顺序固定 ⇒ 同输入同字节；旧仓 zip 的目录形状见 `release/README.md` §3）。
 * @returns {{rows:Array, problems:string[], version:object|null, zipName:string|null}}
 */
export function packPlan(ctx, changed, { zipPath = null } = {}) {
  const problems = [];
  const rows = [];

  for (const b of changed.bins) {
    rows.push({ entry: `BIN/${b.name}`, kind: 'bin', source: `patch.json ← 基线 ${b.baseFrom}`, buf: b.buf, sha256: b.sha256 });
  }
  for (const a of changed.agfs) {
    rows.push({ entry: `AGF/${a.name}`, kind: 'agf', source: `ui-bake 配方 ${a.block} · ${a.file}`, buf: a.buf, sha256: a.sha256 });
  }
  if (changed.agerc) {
    rows.push({ entry: changed.agerc.name, kind: 'agerc', source: changed.agerc.file, buf: changed.agerc.buf, sha256: changed.agerc.sha256 });
  }

  const f = distributionFonts(ctx);
  problems.push(...f.problems);
  for (const x of f.fonts) rows.push({ entry: x.name, kind: 'font', source: x.file, buf: x.buf, sha256: x.sha256 });

  const t = releaseTexts(ctx);
  problems.push(...t.problems);
  for (const x of t.texts) rows.push({ entry: x.name, kind: 'text', source: x.file, buf: x.buf, sha256: x.sha256 });

  // 版本节：**包里必须有当前版本节**（旧仓的 CHANGELOG 与包是一起长出来的，脱节就是发错包）
  const cl = t.texts.find((x) => x.name === 'CHANGELOG.md');
  let version = null;
  if (cl) {
    version = changelogVersion(cl.buf.toString('utf8'));
    if (!version) problems.push('release/CHANGELOG.md 里找不到版本节（规格：`## vX.Y（开发中）` 或 `## vX.Y（YYYY-MM-DD）`）');
    else if (!version.zipName) problems.push(`release/CHANGELOG.md 的版本节形态不合规格：\`## ${version.version}（${version.mark}）\`（标注只能是「开发中」或日期）`);
  }

  const dup = rows.map((r) => r.entry).filter((n, i, a) => a.indexOf(n) !== i);
  if (dup.length) problems.push(`条目重名：${[...new Set(dup)].join(', ')}`);

  const name = zipPath ? path.basename(zipPath) : version?.zipName ?? null;
  const zipPathFinal = zipPath ?? (name ? path.join(ctx.zipDir, name) : null);
  return { rows, problems, version, zipName: name, zipPath: zipPathFinal };
}

/**
 * 写 zip + 同名清单，并**读回复验**（逐条目反解比对；不绿删掉 zip、不留残件）。
 * @returns {{ok:boolean, problems:string[], bytes?:number, sha256?:string, manifestPath?:string, zipPath?:string}}
 */
export function writePack(ctx, plan) {
  const { rows, zipPath } = plan;
  if (!zipPath) return { ok: false, problems: ['算不出版本 ⇒ 不知道 zip 叫什么（用 --zip 显式指定，或修 CHANGELOG）'] };
  const manifestPath = ctx.packManifest ?? zipPath.replace(/\.zip$/i, '.manifest.json');

  let zip;
  try {
    zip = buildZip(rows.map((r) => ({ name: r.entry, data: r.buf })));
  } catch (err) {
    return { ok: false, problems: [`打包失败：${err.message}`] };
  }

  fs.mkdirSync(path.dirname(zipPath), { recursive: true });
  // ★ 先写临时件、读回复验过了再改名 —— 失败时不毁掉上一版 zip
  const tmp = `${zipPath}.tmp`;
  fs.writeFileSync(tmp, zip);

  // ★ 写后回读复验：条目集合 + 每条**逐字节**
  const problems = [];
  try {
    const back = readZip(fs.readFileSync(tmp));
    const want = new Set(rows.map((r) => r.entry));
    for (const n of want) if (!back.has(n)) problems.push(`回读缺条目：${n}`);
    for (const n of back.keys()) if (!want.has(n)) problems.push(`回读多出条目：${n}`);
    for (const r of rows) {
      const got = back.get(r.entry);
      if (got && !got.equals(r.buf)) problems.push(`回读不一致：${r.entry}`);
    }
  } catch (err) {
    problems.push(`回读失败：${err.message}`);
  }
  if (problems.length) {
    fs.rmSync(tmp, { force: true });
    return { ok: false, problems };
  }
  fs.renameSync(tmp, zipPath);

  const sha256 = sha256buf(zip);
  const manifest = {
    schemaVersion: 1,
    _doc: '本文件是**生成物**（发行包的自检记录）：字段语义 / 怎么查怎么改见 `pnpm tools release describe`。由 pnpm tools release pack 写入，不要手改。',
    version: plan.version?.version ?? null,
    mark: plan.version?.mark ?? null,
    zip: path.basename(zipPath),
    zipSha256: sha256,
    entries: rows.map((r) => ({ entry: r.entry, kind: r.kind, source: r.source, bytes: r.buf.length, sha256: r.sha256 })),
  };
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 1)}\n`);
  return { ok: true, problems: [], bytes: zip.length, sha256, manifestPath, zipPath, entries: rows.length };
}

// ─────────────────────────────────────────────────────────── 测试安装树

/**
 * 测试安装树 = **基础树（游戏安装根）** + **变更集覆盖**。
 *
 * 它等价于《安装说明》第 1–5 步：复制一份游戏 → 移出 `AGE-EXTEND.TTF` → 覆盖 BIN / AGF / AGERC.DLL。
 * 差别只有一处：`*.ALF`（7.4 GiB 的只读大件）走**硬链接**而不是真拷贝。
 *
 * ★ 硬链接的代价必须显式说：链接与游戏安装根**是同一个 inode** ⇒ **任何往测试树里写的动作都会改到本体**。
 *   所以本工具只把"我们自己的产物"（BIN / AGF / AGERC）写成真文件，基础树里的件**只读**。
 * @returns {{base:Array, overlays:Array, excluded:Array, dirs:string[], problems:string[]}}
 */
export function installPlan(ctx, changed) {
  const problems = [];
  const base = [];
  const excluded = [];
  const dirs = [];

  if (!fs.existsSync(ctx.baseDir)) {
    problems.push(`基线根不在：${ctx.baseDir}（清单 roots.gameInstall）`);
  } else {
    const entries = fs.readdirSync(ctx.baseDir, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
    for (const e of entries) {
      if (!e.isFile()) { dirs.push(e.name); continue; }
      const why = excludeReason(e.name, ctx.exclude);
      if (why) { excluded.push({ name: e.name, why }); continue; }
      const src = path.join(ctx.baseDir, e.name);
      const hardlink = path.extname(e.name).toUpperCase() === '.ALF' && ctx.alfMode !== 'copy';
      base.push({
        path: e.name,
        action: hardlink ? 'hardlink' : 'copy',
        source: relToRepo(src),
        bytes: fs.statSync(src).size,
      });
    }
  }

  // 覆盖件：先按**基础树里已有的大小写**落（大小写不敏感的文件系统上就是同一个文件；
  // 大小写敏感的机器上也不会凭空多出一份 `so025.AGF` + `SO025.AGF`）
  const baseLower = new Map(base.map((r) => [r.path.toLowerCase(), r.path]));
  const overlays = [];
  const push = (o) => {
    const hit = baseLower.get(o.path.toLowerCase());
    overlays.push(hit ? { ...o, path: hit, replaces: hit } : o);
  };
  for (const b of changed.bins) push({ path: b.name, kind: 'bin', buf: b.buf, sha256: b.sha256, source: 'patch.json' });
  for (const a of changed.agfs) push({ path: a.name, kind: 'agf', buf: a.buf, sha256: a.sha256, source: a.file });
  if (changed.agerc) push({ path: changed.agerc.name, kind: 'agerc', buf: changed.agerc.buf, sha256: changed.agerc.sha256, source: changed.agerc.file });

  // 可选的 LE 启动器（旧仓 install/ 里那份的等价物；**不是**游戏件，是"怎么起这棵树"的说明）
  if (ctx.leCmd) {
    const l = leLauncher(ctx);
    problems.push(...l.problems);
    if (l.buf) push({ path: LE_LAUNCHER_NAME, kind: 'launcher', buf: l.buf, sha256: sha256buf(l.buf), source: '本工具生成（--le-cmd / --le-profile）' });
  }

  const dup = overlays.map((o) => o.path.toLowerCase()).filter((n, i, a) => a.indexOf(n) !== i);
  if (dup.length) problems.push(`覆盖件重名：${[...new Set(dup)].join(', ')}`);

  return { base, overlays, excluded, dirs, problems };
}

/** 读回本工具上次写的安装树清单（决定"能不能就地同步"与"哪些覆盖件已经过时"） */
export function readInstallManifest(p) {
  if (!fs.existsSync(p)) return null;
  try {
    const m = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (m?.schemaVersion !== 1 || !Array.isArray(m.overlays)) return null;
    return m;
  } catch {
    return null;
  }
}

/** 同一个 inode？`ino` 拿不到时退化成"大小 + mtime 相同"（不假装知道） */
function sameFile(a, b) {
  const A = fs.statSync(a);
  const B = fs.statSync(b);
  if (A.ino && B.ino) return A.ino === B.ino && A.dev === B.dev;
  return A.size === B.size && Math.floor(A.mtimeMs) === Math.floor(B.mtimeMs);
}

/**
 * 这个复制件还是不是源的那一份？—— **大小 + mtime（±2 ms）**。
 * ★ 为什么要容差：`utimesSync` 只接受毫秒精度的 `Date`，而 `statSync().mtimeMs` 带亚毫秒小数
 *   ⇒ 写回去会比源**大不到 1 ms**（实测 1791108145543 vs 1791108145542.6853）。
 *   拿 `===` 判就会每次重跑都重拷一遍（幂等性当场失效）。
 */
function sameCopy(src, dst) {
  const A = fs.statSync(src);
  const B = fs.statSync(dst);
  return A.size === B.size && Math.abs(B.mtimeMs - A.mtimeMs) < 2;
}

/**
 * 落盘：基础树（ALF 硬链接 / 其余复制）→ 覆盖件（真文件）→ 清掉上一次留下的过时覆盖件。
 *
 * 顺序是有讲究的：**先清过时覆盖件、再同步基础树、最后写覆盖件** ——
 * 这样"上一轮是覆盖件、这一轮变回基础件"的那个名字会被基础树重新铺回原版（而不是留着旧译文）。
 * @returns {{ok:boolean, problems:string[], stats?:object}}
 */
function installTree(ctx, plan, { force = false, log = () => {}, relabel = false } = {}, state = {}) {
  const outDir = ctx.outDir;
  const manifestPath = ctx.installManifest;
  const problems = [...plan.problems];

  if (fs.existsSync(outDir) && !fs.statSync(outDir).isDirectory()) {
    problems.push(`落点已被一个文件占着：${outDir}`);
  }
  if (problems.length) return { ok: false, problems };

  const existed = fs.existsSync(outDir) && fs.readdirSync(outDir).length > 0;
  const prev = existed ? readInstallManifest(manifestPath) : null;
  if (existed && !prev && !force) {
    return {
      ok: false,
      problems: [
        `${outDir} 已存在且不是本工具建的（没有 ${relToRepo(manifestPath)}）`,
        '要么换 --out，要么先清空它，要么加 --force 表示"我知道里面是什么"',
      ],
    };
  }

  fs.mkdirSync(outDir, { recursive: true });
  const stats = { hardlink: 0, copy: 0, skip: 0, write: 0, prune: 0, bytes: 0, verified: 0 };
  const written = [];
  /** 失败处置：**这一轮新建的树整棵撤掉**（否则会留下一棵"有一半基础件、又没有清单"的假树） */
  const fail = (problems) => {
    if (!existed) fs.rmSync(outDir, { recursive: true, force: true });
    else problems.push('⚠ 这次失败落在同步途中：目标目录可能处于混合状态 —— 重跑一次即可收敛（基础树同步是幂等的）');
    return { ok: false, problems };
  };
  state.fail = fail; // 外层薄壳（writeInstall）兜住意外抛出时也走同一条回滚

  // ★ **先探一次**硬链接能力（一次 link + unlink，只动元数据）：拿不到就直接报，别写了一半才发现
  const firstLink = plan.base.find((r) => r.action === 'hardlink');
  if (firstLink) {
    const probe = path.join(outDir, '.release-link-probe');
    fs.rmSync(probe, { force: true }); // 上次跑到一半留下的探针（只可能在 outDir 里，因为它必须同卷）
    try {
      fs.linkSync(path.join(ctx.baseDir, firstLink.path), probe);
      fs.rmSync(probe, { force: true });
    } catch (err) {
      fs.rmSync(probe, { force: true });
      return fail([
        `硬链接不可用（试的是 ${firstLink.path}）：${err.code ?? ''} ${err.message}`,
        '两种成因，各自有各自的处置：',
        `  ① **不同卷**（EXDEV）：硬链接要求基线根与落点在同一个盘符（现在是 ${path.parse(ctx.baseDir).root} → ${path.parse(outDir).root}）`
          + ' ⇒ 把测试树放到游戏所在的盘上，或加 `--alf copy`（真拷贝，多占 ~7.4 GB）',
        '  ② **权限不足**（EPERM/EACCES）：建硬链接会**改到源文件的链接数**，所以它不是纯读操作 ——'
          + '受限沙箱 / 只读 ACL 下会被拒 ⇒ 用 `--alf copy`，或让这一步在能写游戏目录的环境里跑',
        `  ③ **落点落在沙箱可写范围之外**：这棵子树若被改成 Medium 完整性（\`--relabel-medium\`），`
          + '受限子进程就只能写带 Low 标签的根 ⇒ 见 tools/release.md §3.1（提权跑一次，或把树建到工作区之外）',
      ]);
    }
  }

  // ① 清掉上一轮的过时覆盖件（**只清我们写过的**；名字若回到基础树里则由 ② 重新铺）
  const nowOverlay = new Set(plan.overlays.map((o) => o.path.toLowerCase()));
  const basePaths = new Set(plan.base.map((r) => r.path.toLowerCase()));
  for (const o of prev?.overlays ?? []) {
    if (nowOverlay.has(String(o.path).toLowerCase())) continue;
    const abs = path.join(outDir, o.path);
    if (!fs.existsSync(abs)) continue;
    if (basePaths.has(String(o.path).toLowerCase())) continue; // ② 会重铺，别在这里删
    fs.rmSync(abs, { force: true });
    stats.prune += 1;
    log(`- 过时覆盖件已清：${o.path}`);
  }

  // ② 基础树（★ 已经是覆盖件的名字**不铺基础件** —— ③ 会写它；否则每次重跑都会"复制→再覆盖"一遍）
  for (const r of plan.base) {
    if (nowOverlay.has(r.path.toLowerCase()) && r.action !== 'hardlink') { stats.skip += 1; continue; }
    const src = path.join(ctx.baseDir, r.path);
    const dst = path.join(outDir, r.path);
    if (r.action === 'hardlink') {
      if (fs.existsSync(dst) && sameFile(src, dst)) { stats.skip += 1; continue; }
      // ★ 先删链接再建：**绝不能**写穿到本体（同 inode）
      if (fs.existsSync(dst)) fs.rmSync(dst, { force: true });
      try {
        fs.linkSync(src, dst);
      } catch (err) {
        return fail([
          `硬链接失败：${r.path} —— ${err.code ?? ''} ${err.message}`,
          '（预探过了却在中途失败 ⇒ 多半是并发改动了游戏目录；重跑一次）',
        ]);
      }
      stats.hardlink += 1;
    } else {
      const ss = fs.statSync(src);
      if (fs.existsSync(dst) && sameCopy(src, dst)) { stats.skip += 1; continue; }
      fs.copyFileSync(src, dst);
      fs.utimesSync(dst, ss.atime, ss.mtime); // 保住来源时间戳（也让上面的"跳过"判据成立）
      stats.copy += 1;
      stats.bytes += ss.size;
    }
  }

  // ③ 覆盖件
  for (const o of plan.overlays) {
    const dst = path.join(outDir, o.path);
    const old = fs.existsSync(dst) ? sha256buf(fs.readFileSync(dst)) : null;
    if (old === o.sha256) { stats.skip += 1; continue; }
    fs.writeFileSync(dst, o.buf);
    stats.write += 1;
    stats.bytes += o.buf.length;
    written.push(o.path);
    log(`+ ${o.path}`);
  }

  // ④ 写后回读复验（覆盖件逐字节 + ALF 逐个 ino）
  const verifyProblems = [];
  for (const o of plan.overlays) {
    const dst = path.join(outDir, o.path);
    if (!fs.existsSync(dst)) { verifyProblems.push(`回读缺覆盖件：${o.path}`); continue; }
    if (sha256buf(fs.readFileSync(dst)) !== o.sha256) verifyProblems.push(`回读不一致：${o.path}`);
    else stats.verified += 1;
  }
  for (const r of plan.base) {
    if (r.action !== 'hardlink') continue;
    const dst = path.join(outDir, r.path);
    if (!fs.existsSync(dst) || !sameFile(path.join(ctx.baseDir, r.path), dst)) verifyProblems.push(`回读：${r.path} 不是硬链接（或链错了对象）`);
  }
  if (verifyProblems.length) {
    for (const p of written) fs.rmSync(path.join(outDir, p), { force: true }); // 回滚本次覆盖件
    return fail(verifyProblems);
  }

  // ⑤ 清单（**生成物**：记录这一棵树是怎么来的；也是下一次同步的"上一轮"）
  const manifest = {
    schemaVersion: 1,
    _doc: '本文件是**生成物**（测试安装树的自检记录）：字段语义 / 怎么查怎么改见 `pnpm tools release describe`。由 pnpm tools release install 写入，不要手改。',
    baseDir: ctx.baseDir,
    outDir,
    rows: [
      ...plan.base.map((r) => ({ path: r.path, action: r.action, kind: 'base', bytes: r.bytes })),
      ...plan.overlays.map((o) => ({ path: o.path, action: 'write', kind: o.kind, bytes: o.buf.length, sha256: o.sha256, source: o.source })),
    ],
    overlays: plan.overlays.map((o) => ({ path: o.path, kind: o.kind, sha256: o.sha256, source: o.source })),
    excluded: plan.excluded,
  };
  fs.mkdirSync(path.dirname(manifestPath), { recursive: true });
  fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 1)}\n`);

  // ⑤ 环境口径：Low 完整性标签（详见 lowIntegrityLabel 的注释 —— 它会让 LE 起不来）
  const warnings = [];
  let relabeled = null;
  const probe = path.join(outDir, 'AGE.EXE');
  const label = lowIntegrityLabel(fs.existsSync(probe) ? probe : outDir);
  if (label.error) warnings.push(`完整性标签没查出来（icacls 跑不起来：${label.error}）—— 若这棵树要给 Locale Emulator 用，留意 lowLabelAdvice`);
  else if (label.low) {
    if (relabel) {
      const r = relabelMedium(outDir);
      relabeled = r.ok ? 'ok' : r.reason;
      if (!r.ok) warnings.push(...lowLabelAdvice(outDir), `  ⇒ --relabel-medium 失败：${r.reason}`);
    } else {
      warnings.push(...lowLabelAdvice(outDir));
    }
  }

  return { ok: true, problems: [], stats, manifestPath, outDir, warnings, relabeled };
}

/**
 * 落盘（**唯一写入口**）。
 * ★ 为什么要一层薄壳：落盘的每一步都可能被**环境**挡下（不同卷 / 权限 / 目标子树被改成 Medium 完整性后
 *   落在受限沙箱的可写范围之外，见 `tools/release.md` §3.1）—— 整段兜住，出错走同一个 `fail()`
 *   （新建的树整棵撤掉、就地同步的如实报"可能混合"），**不留半棵树**。
 */
export function writeInstall(ctx, plan, opts = {}) {
  const state = {};
  try {
    return installTree(ctx, plan, opts, state);
  } catch (err) {
    const extra = [];
    if (err.code === 'EACCES' || err.code === 'EPERM') {
      extra.push('（权限类错误：目标子树若已改成 **Medium 完整性**，它就落在受限沙箱的**可写范围之外**了 ——');
      extra.push('  处置见 tools/release.md §3.1：提权跑一次，或把树建到工作区之外）');
    }
    const problems = [`落盘过程中出错：${err.code ?? ''} ${err.message}`, ...extra];
    return typeof state.fail === 'function' ? state.fail(problems) : { ok: false, problems };
  }
}

// ─────────────────────────────────────────────────────────── 自描述

export const DOMAIN = {
  id: 'release',
  title: '发行打包（测试安装树 / 发给玩家的 zip）',
  tool: 'tools/release.mjs',
  data: [
    'data/translations/patch.json（只读：BIN 键集 + resultSha 判据）',
    'tools/ui-bake/recipes/*.json（只读：AGF 进包集合）· dist/ui-bake/*.AGF（只读：AGF 字节，由 ui-bake build 产出）',
    'corpus/assets/agerc/AGERC.DLL · corpus/assets/fonts/Amayui-CN_cnjp*.ttf（只读）',
    'release/CHANGELOG.md · release/安装说明.md（只读：随包文本；版本节决定 zip 名）',
    '<gameInstall>（只读：基础树；ALF 走硬链接）',
    'dist/install/ + dist/install-manifest.json（生成物）· dist/patch/<版本>.zip + .manifest.json（生成物）',
  ],
  access: 'rw（两条写路径都在本工具：install / pack；缺省 dry-run，--write 才落盘；写后回读复验，不绿回滚）',
};

export const OPERATIONS = [
  { name: 'describe', argv: ['--describe'], mutates: false, summary: '自描述：变更集从哪来 / 包里有什么 / 不变量 / 操作' },
  { name: 'plan', argv: ['--plan'], mutates: false, summary: '执行计划（不落盘）：`plan install` / `plan pack`' },
  { name: 'install', argv: ['--install'], mutates: true, summary: '同步出**测试安装树**（旧仓 install/ 的等价物；ALF 硬链接，其余复制）[--write]' },
  { name: 'pack', argv: ['--pack'], mutates: true, summary: '打成**发给玩家的 zip**（旧仓 patch/ 的等价物；含自检）[--write]' },
];

export const INVARIANTS = [
  { id: 1, text: 'BIN 集 = patch.json 的键集（**不许**另一份同步清单：旧仓 patch.config.json 就是这么漂掉的）', enforcedBy: ['collectChanged()', 'tools/test/release.test.mjs#★ pack：条目表只由真源算出来（键集 / AGF 集合 / 版本节）'] },
  { id: 2, text: '每一支 BIN 都必须与 patch 的 `resultSha` 逐字节相同（重建 ≠ 记录 ⇒ 一个字都不写）', enforcedBy: ['collectChanged() 的 resultSha 复核', 'writePack() 的读回复验'] },
  { id: 3, text: 'AGF 集合 = 有配方的块；字节来自 `ui-bake build` 的产物（缺件 ⇒ 报"先跑哪条命令"，不自己凑图）', enforcedBy: ['collectChanged()'] },
  { id: 4, text: '基础树里的 `*.ALF` 是**硬链接**（同一个 inode）；其余是复制 —— 且 ALF 永不作为覆盖件被写', enforcedBy: ['installPlan()', 'writeInstall() 的回读 ino 比对', 'tools/test/release.test.mjs#★ install：ALF 硬链接、其余复制、覆盖件是真文件'] },
  { id: 5, text: '`dist/install/` 里出现的文件只有两种来源：基础树（复制/硬链接）与变更集覆盖件；上一轮的过时覆盖件必须清掉', enforcedBy: ['writeInstall() 的 prev-manifest 清理'] },
  { id: 6, text: '包里有且只有：`BIN/` · `AGF/` · `AGERC.DLL` · `Amayui-CN_cnjp*.ttf` · `CHANGELOG.md` · `安装说明.md`（缺件 / 多件 ⇒ 红）', enforcedBy: ['packPlan()', 'tools/test/release.test.mjs#★ pack：条目表只由真源算出来（键集 / AGF 集合 / 版本节）'] },
  { id: 7, text: '`CHANGELOG.md` 必须有当前版本节（`## vX.Y（开发中）` / `## vX.Y（YYYY-MM-DD）`）—— 没版本节就不出包', enforcedBy: ['packPlan() 的 changelogVersion()'] },
  { id: 8, text: '打包是**确定性**的：同输入 ⇒ 同字节（固定时间戳、固定条目序、无 generatedAt）', enforcedBy: ['tools/lib/zip.mjs', 'tools/test/release.test.mjs#★ pack：同输入同字节（确定性）'] },
  { id: 9, text: '旧仓的同步清单 / 产物**一律不迁**（patch.config.json 是第二真源；patch/BIN、patch/AGF 是产物）', enforcedBy: ['release/README.md §6'] },
];

export function describe() {
  return {
    file: '（无自有 JSON：本工具只**读**三处真源、只**写** dist/ 下的生成物）',
    purpose:
      '把「当前所有变更过的资源」铺成两种形状：测试安装树（dist/install/）与发行包（dist/patch/<版本>.zip）。' +
      '变更集 = patch.json 的键（BIN）+ ui-bake 的配方集合（AGF）+ corpus 里的 AGERC/字体；**不存在第四处同步清单**。',
    changedSet: [
      { kind: 'bin', from: 'data/translations/patch.json 的键', note: '字节 = 基线（gameInstall 的散装/ALF）+ patch 重建；逐支复核 resultSha' },
      { kind: 'agf', from: 'tools/ui-bake/recipes/*.json（集合）→ dist/ui-bake/<块>.AGF（字节）', note: '烧图是 ui-bake 的活（headless Chrome），本工具只消费产物' },
      { kind: 'agerc', from: 'corpus/assets/agerc/AGERC.DLL', note: '本版用入库的可信产物；自建链见 REQ-01M411CSDXDVGTP83BPS6TNV48' },
      { kind: 'font', from: 'corpus/assets/fonts/Amayui-CN_cnjp*.ttf', note: '只进**发行包**，不进测试树（字体是装进系统的，安装说明第 6 步）' },
      { kind: 'text', from: 'release/CHANGELOG.md · release/安装说明.md', note: '只进发行包；逐字节复制' },
    ],
    packShape: [
      'BIN/<脚本>.BIN（N = patch 的键数）',
      'AGF/<块>.AGF（N = 有配方的块数）',
      'AGERC.DLL',
      'Amayui-CN_cnjp.ttf · Amayui-CN_cnjp-Bold.ttf',
      'CHANGELOG.md · 安装说明.md',
    ],
    installShape: [
      '基础树：<gameInstall> 的**顶层文件**（子目录不复制 —— 测试树是平的，与旧仓 install/ 同形）',
      '  *.ALF ⇒ **硬链接**（7.4 GiB 只读大件；同卷要求；`--alf copy` 可改成真拷贝）；其余 ⇒ 复制（并保住来源 mtime）',
      '覆盖件：变更集里的 BIN / AGF / AGERC.DLL（真文件，**永不**硬链接）',
      '可选：`--le-cmd <LEProc.exe> [--le-profile <guid>]` ⇒ 写一份 `启动游戏-LE.cmd`（`cd /d "%~dp0"` 再交给 LE 起 AGE.EXE）',
      `排除：${INSTALL_EXCLUDES.map((e) => e.name ?? String(e.re)).join(' · ')}（每条的理由见源码里的 INSTALL_EXCLUDES）+ 命令行 --exclude`,
      '★ 硬链接 = 同一个 inode ⇒ **别往测试树里写东西**（本工具只写自己的产物，基础树只读）',
    ],
    invariants: INVARIANTS,
    operations: OPERATIONS,
    writePath: '唯一写入口是本工具的 install / pack（缺省 dry-run；--write 才落盘，且写后回读复验，不绿回滚）。除此之外只有 corpus / patch / ui-bake 各自的写入口能改它们的真源。',
    howTo: [
      'pnpm tools release describe',
      'pnpm tools release plan install    # 测试树计划（不落盘）',
      'pnpm tools release plan pack       # 发行包计划（不落盘）',
      'pnpm tools release install --write # → dist/install/ + dist/install-manifest.json',
      'pnpm tools release pack --write    # → dist/patch/<版本>.zip + 同名 .manifest.json',
      'pnpm test                          # 基建契约：tools/test/release.test.mjs',
    ],
  };
}

export function describeText(d = describe()) {
  const L = [];
  L.push('# 发行打包 —— 自描述（由控制脚本给出，文档不复述 schema）');
  L.push('');
  L.push(`用途：${d.purpose}`);
  L.push('');
  L.push('## 变更集从哪来（★ 没有第四处同步清单）');
  for (const c of d.changedSet) L.push(`* \`${c.kind}\` ← ${c.from}\n  ${c.note}`);
  L.push('');
  L.push('## 包里有什么（顺序固定 ⇒ 同输入同字节）');
  for (const s of d.packShape) L.push(`* ${s}`);
  L.push('');
  L.push('## 测试安装树长什么样');
  for (const s of d.installShape) L.push(`* ${s}`);
  L.push('');
  L.push('## 不变量（含"谁在守它"）');
  for (const inv of d.invariants) L.push(`${inv.id}. ${inv.text}　—　${inv.enforcedBy.join(' + ')}`);
  L.push('');
  L.push('## 操作');
  for (const o of d.operations) L.push(`* \`${o.name}\`${o.mutates ? '（会写）' : ''} —— ${o.summary}`);
  L.push('');
  L.push(`写入口：${d.writePath}`);
  L.push('');
  L.push('## 怎么查 / 怎么改');
  for (const h of d.howTo) L.push(`  ${h}`);
  return `${L.join('\n')}\n`;
}
